name: Build U-Boot

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        # Sửa: Thay thế ./lab4-uboot thành . (Build context là thư mục hiện tại)
        run: docker build -t bbb-uboot . 

      - name: Run U-Boot build inside container
        # Sửa: Thay thế /lab4-uboot:/build thành /u-boot:/build
        # Lưu ý: Vì build_uboot.sh nằm ngoài thư mục u-boot, 
        # ta mount thư mục gốc và chạy script từ đó
        run: docker run --rm -u 1001 -v ${{ github.workspace }}:/build bbb-uboot ./build_uboot.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uboot-build
          # Sửa: Thay thế lab4-uboot/u-boot/ thành u-boot/
          path: u-boot/{MLO,u-boot.img}