name: Build U-Boot

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t bbb-uboot ./lab4-uboot

      - name: Run U-Boot build inside container
        run: docker run --rm -v ${{ github.workspace }}/lab4-uboot:/build bbb-uboot ./build_uboot.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uboot-build
          path: lab4-uboot/u-boot/{MLO,u-boot.img}
